falcon-linux-deploy.sh
=> Add ability to specify N-5 deployments

falcon-linux-deploy.sh
=> Install sensor version if update policy name is set

falcon-linux-deploy.sh
Fixes #20 by using `name.raw` filter - which allows the passing of Sensor update policy names with spaces. Also added an additional sanity check to ensure we were able to find the supply policy name, otherwise fail with appropriate message.
=> Fixes issue with sensor update policy name query

README.md, falcon-linux-deploy.sh
- Rename to falcon_sensor_version_decrement to better reflect N-x support
=> Rename falcon_sensor_version variable

falcon-linux-deploy.sh
Added Logic to for 'Oracle Linux Server' to output 'Oracle'
=> Added logic to handle /etc/*release for Oracle

falcon-linux-deploy.sh
=> Fix dash shell support

falcon-linux-deploy.sh
=> Add AWS SSM functionality

falcon-linux-deploy.sh
=> Add ability to remove installed package

.github/workflows/psscriptanalyzer.yml, .github/workflows/shellcheck.yml, bash/README.md, bash/install/README.md, bash/install/falcon-linux-install.sh, bash/install/falcon-linux-uninstall.sh, powershell/README.md, powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1
- Minor updates to uninstall function in falcon-linux-install.sh
- Add Linux uninstall script
- Add Windows Powershell scripts
- Add Windows Powershell CI
=> Update linux scripts and add Windows Powershell scripts

powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1
- Use regex for uninstaller
- Use booleans instead of string
- Add uninstall function for single script instances
=> Update PS scripts

bash/install/falcon-linux-install.sh
=> Do not disclose sensitive information on the command-line

bash/README.md, bash/containers/README.md, bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Added Bash script for pulling down the latest falcon container images to a users local docker images based on my original project at: https://github.com/TomRyan-321/falcon-container-sensor-pull which I'll archive and redirect to here once merged
=> Falcon container pull bash script

powershell/install/falcon_windows_install.ps1
=> Fix PS memberCID invocation

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
- Add features version and credential dump features per customer request
- Support dash shell
- Shrink amount of required flags to configure
- Add support for podman and skopeo
- Fix credentials output with curl in script
- Standardize vars to be consistent
- Update readme
=> Update container pull script for customer needs

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
The CS registry is static and not tied to a cloud.
=> fixing registry url

bash/install/falcon-linux-install.sh
- Adds arch filter to ensure we download the appropriate packages now that they are intertwined in the api
- Minor code refactoring
=> Updates to sensor-install and some clean up

bash/install/falcon-linux-install.sh
=> Fix Debian issue in cs_os_name

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
There was an issue with users of GovCloud api trying to pull the container sensor but the registry attempts would fail. 
This was identified by the following delta:
```diff
- registry.laggar.gcw.crowdstrike.com/falcon-sensor/us-gov-1/release/...
+ registry.laggar.gcw.crowdstrike.com/falcon-sensor/govcloud/release/...
```
Rather than using the same FALCON_CLOUD convention as the non-govcloud registries have, this one uses `govcloud` instead.
=> Fixed issue with API mismatch on FALCON_CLOUD registry url path

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/falcon-linux-install.sh
=> Initial commit for testing new curl syntx

bash/install/falcon-linux-install.sh
Fixes #90. Tested on both Ubuntu 22.04 x64_64 and arm64.
=> Fix Ubuntu 22.04 arm64 install

bash/install/README.md, bash/install/falcon-linux-install.sh
Adding Falcon Sensor options to allow customization like tags, log level, proxy, type of sensor and backend
=> Add linux installer options

powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1
PR fixes issues associated with uninstall and install scripts in powershell
=> Fix powershell issues

powershell/install/falcon_windows_uninstall.ps1
=> improved error logging for maint token

powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1
=> add `ProvToken` and `ProvWaitTime` to install.ps1

powershell/install/README.md, powershell/install/falcon_windows_install.ps1
=> add the ability to pass tags to the installer

.github/workflows/ci-linux.yml, molecule/bash_install/converge.yml, molecule/bash_install/molecule.yml, molecule/bash_install/prepare.yml, molecule/bash_install/verify.yml, molecule/bash_install_decrement/converge.yml, molecule/bash_install_decrement/molecule.yml, molecule/bash_install_decrement/prepare.yml, molecule/bash_install_decrement/verify.yml, molecule/bash_install_only/converge.yml, molecule/bash_install_only/molecule.yml, molecule/bash_install_only/prepare.yml, molecule/bash_install_only/verify.yml, molecule/bash_install_policy/converge.yml, molecule/bash_install_policy/molecule.yml, molecule/bash_install_policy/prepare.yml, molecule/bash_install_policy/verify.yml
Closes #123 
Add CI testing for the linux scripts using the molecule framework.....
=> Add ci testing linux

powershell/install/falcon_windows_uninstall.ps1
RemoveHost is a switch so we do not need to pass a value.
=> Update script example

.github/workflows/ci-windows.yml, molecule/pwsh_install_ccid/INSTALL.md, molecule/pwsh_install_ccid/converge.yml, molecule/pwsh_install_ccid/molecule.yml, molecule/pwsh_install_ccid/prepare.yml, molecule/pwsh_install_ccid/verify.yml, powershell/install/falcon_windows_install.ps1
Closes #141 
This PR introduces the FalconCid parameter to the powershell install script. It also adds a test case to ensure we have coverage in molecule.
=> Adding ability to pass in CCID + molecule test

.github/workflows/ci-linux.yml, .github/workflows/ci-windows.yml, bash/install/falcon-linux-install.sh
Fixes #148  and accounts for new molecule testing changes.
=> Fixed issue associated with bash install and sc2086

bash/install/README.md, powershell/install/README.md, powershell/migrate/README.md
=> Bumping v1.1.1

bash/install/README.md, powershell/install/README.md, powershell/migrate/README.md
=> Bumping v1.1.2

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/falcon-linux-install.sh, powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1, powershell/migrate/falcon_windows_migrate.ps1
Closes #118 
This adds the user-agent header to oauth calls for the scripts that use it.
=> Adds user-agent string

powershell/install/README.md, powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1, powershell/migrate/README.md, powershell/migrate/falcon_windows_migrate.ps1
Fixes #169 
This PR adds `-Verbose` mode functionality to facilitate better troubleshooting for the powershell scripts. It also updates the existing powershell docs with a new troubleshooting section.
=> Better logging powershell support

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/falcon-linux-install.sh
Fixes #174
This PR enhances the logic used to test for curl version compatability.
=> Update curl version logic

bash/containers/falcon-container-sensor-pull/README.md
We are linking to this script from the Falcon Console docs. I wanted to just clean up a couple things, missing markup, bold areas that should be highlighted, rephrase a couple things.
=> kweishaar: fixed missing markup, small edit for clarity

bash/install/falcon-linux-install.sh
Fixes #179 
This pull request includes a set of optimizations and refactorings to the Falcon Linux installer script, improving both its efficiency and maintainability.
Changes introduced:
1. **API Request URL Update:** The API request URL was updated to include a version sorting parameter. This allows us to handle the versioning in a simpler way, reducing the complexity of the code.
1. **Installer Detection Logic Refactoring:** The installer detection logic was refactored to reduce its complexity. This change simplifies the code and makes it more readable and maintainable.
1. **Descriptive Error Messages:** The error messages were adjusted to be more descriptive and specific. This helps in better identifying the issues when errors occur.
1. **Amazon Linux Version Handling:** The handling …
=> Refactor Falcon Linux Installer Script for better support

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Added command-line option "--kubernetes-protection-agent" to support pulling kpagent image
=> Add support for Kubernetes Protection Agent

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
remote repository name for  `--copy myregistry.com/mynamespace` command was incorrect. It should be `myregistry.com/mynamespace/<sensor-name>`.
=> fix copy image command in script falcon-container-sensor-pull.sh

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Small fix to display correct KP creds
=> Add dump-credentials support for Kubernetes Protection

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/README.md, bash/install/falcon-linux-install.sh, powershell/install/README.md, powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1, powershell/migrate/README.md, powershell/migrate/falcon_windows_migrate.ps1
Bumping before introducing new breaking changes with #193
=> bump 1.1.5

.github/workflows/psscriptanalyzer.yml, .github/workflows/release.yml
- Update psscriptanalyzer action to use the official MSFT action
- Update release action to create a zip of the powershell install/uninstall scripts
=> feat: update release and psscriptanalyzer actions

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Use gov1 for govcloud registry paths.
Update README to include the needed scope to pull the KPA
=> Update govcloud registry url

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
I've added the pull-token generation.
Design question: Line 399, I've added a new line break which make the script ending with a new line.
so it's nice for someone looking to get the image pull token
BUT for automation it force scripts to use `echo -n $()` to remove the new line break
I think it's better to keep the new line break => any comment on this ?
=> Add Kubernetes Pull Token for specific sensor_type

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/README.md, bash/install/falcon-linux-install.sh, powershell/install/README.md, powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1, powershell/migrate/README.md, powershell/migrate/falcon_windows_migrate.ps1
=> bump v1.1.8

bash/containers/falcon-container-sensor-pull/README.md
When #201 was merged, the README was not updated with the new param
=> update README about the --get-pull-token param

README.md, SUPPORT.md
Adds support statement to the project
=> docs: add statement of support

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This PR properly formats the shell script and fixes some validation checks.
=> fix: cleanup container script formatting

.github/workflows/shell_format.yml, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/falcon-linux-install.sh, bash/install/falcon-linux-uninstall.sh
Add consistency to our shell formatting + fix existing inconsistencies.
=> chore: add workflow for shell formatting

powershell/install/falcon_windows_install.ps1
=> fix: fix issue with redirect on powershell install script

powershell/install/falcon_windows_uninstall.ps1
Adds proxy support to powershell uninstallation script
=> feat: add proxy support to pwsh uninstall script

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Making the output simpler to parse for automation
=> update script output to make it more usuable with automation

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Similar to how Skopeo list tags and provides the repository path, this commit adds that to our list-tags output.
=> feat(container-sensor-pull): add repository to list-tags output

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Minor updates to ensure our readme and help usage section are in sync
=> docs(container-sensor-pull): update readme and help to be in sync

powershell/install/falcon_windows_install.ps1
This is the same fix for the uninstall script.
=> fix(pwsh_install): fixes write-verboselog exception message issue

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This fixes an issue with listing tags for the new multi-arch falcon-sensor image.
=> fix(container-sensor-pull): fix issue with listing tags and multi-arch

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/README.md, bash/install/falcon-linux-install.sh, bash/install/falcon-linux-uninstall.sh, powershell/install/README.md, powershell/migrate/README.md
Closes #293 
Updates the respective READMEs for each tool + minor updates to error messages pertaining to situation where this might be the cause.
=> docs: readme updates to make cloud region auto-discovery clearer

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This change adds a case statement to better reflect the images that require a different sorting mechanism. It includes the appropriate images now.
Fixes #302
=> fix(container-pull): add falcon-imageanalyzer to proper sort formatting

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes #304 #306 
This PR fixes a current issue affecting Artifactory registries and multi-arch images in which the digest of the images are being displayed as tags. However, this poses a problem become the digest is not a valid tag format. A recent CVE exposed this and now tools such as Skopeo and Podman have patched this which is causing the listing tag issue with Artifactory.
Also added a better way to get the version of the script currently being used.
=> fix(container-pull): fix issue with artifactory incorrect tags + add version info

bash/install/falcon-linux-install.sh
Fixes #312
Simplifies FQL to ensure we get the proper architecture
=> fix(bash install): update falcon-linux-install.sh role to take advantage of v2 sensor_download module

bash/containers/falcon-container-sensor-pull/README.md
=> docs(container-pull): update verbiage surrounding kernel mode for daemonset

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
When used in testing environment we want to run falcon-container-sensor-pull.sh not only against release but stage repository as well
=> CSPG-36014 Support download for stage containers

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This PR cleans up existing API scopes and makes it easier to know what scopes are needed depending on the sensor type. This allows for better support of least privilege. Also added better handling of catching errors associated with 403 API scope issues.
=> fix(container-pull): update scopes and better error handling

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This PR adds the ability to pull down the FCS CLI tool from our registries.
=> feat(container-pull): add fcs type for iac image pull

bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes issue with curl -f forcing an early exit of the script with no warning as to potential issues with scopes. Since -f captures anything over a 400 as an exit code 22, this was prematurely cancelling the script with no appropriate reason.
=> fix(container-pull-script): fix logic surrounding -f for curl command

powershell/migrate/falcon_windows_migrate.ps1
=> fix(pwsh-migrate): remove unnecessary paren ending and add space

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This PR was in response to #368 
If a copy operation happens - then echo out the destination path in case someone wants to see it.
=> chore(container-pull-script): echo destination path and update list-tags verbiage

powershell/install/falcon_windows_uninstall.ps1
- Allows for support of new sensor name
=> fix: use regex for uninstaller name and search results by regex

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh, bash/install/README.md, bash/install/falcon-linux-install.sh, bash/install/falcon-linux-uninstall.sh, powershell/install/README.md, powershell/install/falcon_windows_install.ps1, powershell/install/falcon_windows_uninstall.ps1, powershell/migrate/README.md, powershell/migrate/falcon_windows_migrate.ps1
Includes fix for Windows uninstaller issue
=> chore: bump v1.7.0

powershell/migrate/falcon_windows_migrate.ps1
=> fix(pwsh migrate): fix regex for uninstaller

bash/containers/falcon-container-sensor-pull/README.md, bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Closes #384
This PR adds the `falcon-jobcontroller` and `falcon-registryassessmentexecutor` images used for Self Hosted Registry Assessments.
=> feat(container-pull-script): add new SHRA images

powershell/install/falcon_windows_uninstall.ps1, powershell/migrate/falcon_windows_migrate.ps1
- Eliminates the need for separate regex for windows sensor uninstall
=> chore: match regex to ansible uninstall regex

powershell/install/README.md, powershell/install/falcon_windows_install.ps1, powershell/migrate/README.md, powershell/migrate/falcon_windows_migrate.ps1
closes #398
The correct sensor arg is supposed to be /norestart.
=> fix(pwsh): replace /noreboot with /norestart

.github/workflows/bash_install.yml, .github/workflows/bash_install_decrement.yml, .github/workflows/bash_install_only.yml, .github/workflows/bash_install_policy.yml, .github/workflows/bash_migrate.yml, .github/workflows/pwsh_install_ccid.yml, .github/workflows/pwsh_install_policy.yml, .github/workflows/pwsh_migrate.yml, .github/workflows/pwsh_uninstall.yml
Sometimes the powershell jobs take a little longer
=> ci: increase timeout
