- falcon-linux-deploy.sh
Fixes #19 by adding `-f` option to the falconctl command for setting the --cid option.
> Fixes issue with register command failing after running script again

- falcon-linux-deploy.sh
Majority of Linux do have LSB package, using it to grab OS name and version can reduce the chances of failure from this script.
> Added OS name and release capture via LSB

- bash/install/falcon-linux-install.sh
Two changes are required - one to recognize the OS name and another to convert the Amazon Linux version to mapping recognized by the Falcon sensor.
Amazon has versions like 2018.03 for Amazon Linux 1
> Amazon Linux 1 support

- bash/install/falcon-linux-install.sh
After chatting with @redhatrises  - this issue was an oversight when copying over from the functionality from another script. There are 2 options that we can use to fix this:
1. The current fix simply ensures that we don't call the `aws_ssm_parameter` function unless it's an `aws_instance`. 
2. Or..rather than use the `aws_instance` variable check, we can opt to use an environmental variable such as `FALCON_AWS_SSM      (default: false)`, and then call the `aws_ssm_parameter` function when this env variable is true.
I'm open to suggestions.
> Added if statement to check if instance is aws

- bash/install/falcon-linux-install.sh
Actually the deployment in other region is not working (US-1 is the main region), The CID is computed before the region checks which generate this error:
`Falcon Sensor Install  ... [ Ok ]
Falcon Sensor Register ... "{code:401,message:accessdenied,invalidbearertoken}" failed checksum validation
ERROR: failed to process the option --cid
Usage: falconctl -g GET_OPTIONS
falconctl -s [ -f ] SET_OPTIONS
falconctl -d [ -f ] DEL_OPTIONS
where GET_OPTIONS := { --cid for CustomerId |
`
So the sensor is downloaded but the CID is not set due to the compute done before the region check.
This PR fix this issue.
> Move the cs_falcon_cid after the region check

- bash/install/falcon-linux-install.sh
fixes #76 
The os_version - arm64 shouldn't have been removed from the last commit.
> Fix issue with arm64 os_version

- powershell/install/falcon_windows_install.ps1
changed api scope reference from 'sensor-installers:read' to 'sensor-download:read' to match naming used in dashboard
> Update API reference field

- bash/install/README.md
- bash/install/falcon-linux-install.sh
Based off #88 
This PR allows a user to only install the sensor without additional configuration/registrations.
> Add sensor install only functionality

- bash/install/falcon-linux-install.sh
This PR fixes an issue affecting RHEL family only. For RHEL based systems, you can see a few different variations for the`os:` output of the sensor query. This ensures we capture any RHEL based os version to ensure we account for RHEL 9, arm, and x64.
Example filter w/ change:
```
'filter=os:"*RHEL*"+os_version:~"arm64"'
```
This is also consistent with Ansible/Puppet/Chef
> API for RHEL/.. os filter is inconsistent

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
- bash/install/falcon-linux-install.sh
- Check if sensor is already running and exiting with code 0 if it's the case
- fixing the shellcheck exit error (the usage function already have the exit command).
> Check if sensor is already running + fix shellcheck

- bash/install/falcon-linux-install.sh
Fixes #108 
There is some weird issue when trying to have a case statement inside and if block, inside a shell expression $(). This keeps the same logic, just moves the if statements outside the expansion to allow the case to work as intended.
> Fix issue with case inside if statement inside shell expansion

- bash/install/falcon-linux-install.sh
Fixes #116 
This PR adds support for the s390x IBM zLinux platform that was recently released by our sensor API's. This will prevent incorrect sensors being downloaded due to wrong architecture.
> Fixes issue with s390x support

- powershell/install/README.md
- powershell/install/falcon_windows_uninstall.ps1
This PR addresses the following issues:
- #103 
- Adds support to retrieve the uninstall/maintenance token from the API.
- This should make it easier when uninstalling multiple systems w/o using a bulk maintenance token. 
- #104 
- Adds the ability to hide (send to trash) the host from the Falcon console UI. 
- This provides the ability to prevent duplicate hosts on the Falcon console, as well as an easy way to keep the console clean.
- Added API authentication support
- Added error code handling to provide better messaging
- Added the ability to get the AID
Co-authored: @carlosmmatos
> Powershell - Uninstall script major updates

- README.md
Now that we have integration tests for linux and windows install scripts, we can add a status badge for quick overview of pipeline status.
> Adding status badge for current integration tests

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This will just print out the API response as JSON if you couldn't get a token for `docker login`, rather than trying to log in using an empty string and getting a generic failure message.
> Handle failed Crowdstrike API authentication slightly more gracefully

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Reverts CrowdStrike/falcon-scripts#129
```
{
"meta": {
"query_time": 9.6e-8,
"powered_by": "cwppcontainersecurityapi",
"trace_id": "dd418306-REDACTED-ad4fec919bd5"
},
"resources": [
{
"token": "REDACTED"
}
],
"errors": []
}
```
it will always die as `"errors": []` will be always there:
```
if echo "$TOKEN_RESPONSE" | grep -qw "errors"; then
```
> Revert "Handle failed Crowdstrike API authentication slightly more gracefully"

- .github/workflows/release.yml
Closes #114 
Add a GH action to automate uploading script artifacts to a release.
> Adding workflow to add scripts as artifacts to releases

- bash/install/falcon-linux-install.sh
IMDSv2 on AWS requires token retrieval for metadata
> IMDSv2 Support

- .github/workflows/ci-linux.yml
- molecule/bash_install/converge.yml
- molecule/bash_install_decrement/converge.yml
- molecule/bash_install_only/converge.yml
- molecule/bash_install_policy/converge.yml
Based on #157 fix - this allows the centos7 workflow to run since that uses a legacy version of curl.
> Adds newly added env var for legacy curl check

- .github/workflows/ci-linux.yml
- .gitignore
- molecule/pwsh_install_ccid/molecule.yml
- molecule/pwsh_install_policy/converge.yml
- molecule/pwsh_install_policy/molecule.yml
- molecule/pwsh_migrate/molecule.yml
Recent changes to vagrant boxes and molecule plugins have caused the windows CI jobs to fail.
> Fix molecule issues

- powershell/install/falcon_windows_install.ps1
- powershell/migrate/falcon_windows_migrate.ps1
Fixes #158 
If a MemberCID is provided, use that as the CID for provisioning a new instance.
> Allowing proper use of member_cid if requested

- powershell/install/falcon_windows_install.ps1
- powershell/install/falcon_windows_uninstall.ps1
- powershell/migrate/falcon_windows_migrate.ps1
Fixes #158 
This PR reverts the previous PR that was supposed to address this issue. Instead, the problem was how the member_cid oauth2 param was being passed.
> Fix membercid issue

- powershell/install/falcon_windows_install.ps1
closes #167 
This PR introduces a new enhanced version of the PowerShell installation script. Numerous changes were implemented to bring it more inline with the uninstall and migrate script. Big changes:
- Instead of using the System.net.webclient to handle API calls, we are now using Invoke-WebRequest to provide us with error handling and better control of the data.
- FalconCloud is the same as the other scripts. We now default to autodiscover, and use short names rather than the full url as it was before.
- Introduction to the Error Handling/Formatting functions from the other scripts
- Better logging
- Fixed flow of getting sensor version
> PowerShell install script enhancements

- bash/install/falcon-linux-install.sh
Remove quotes on `cs_falcon_args` and disable shellcheck alert as otherwise no tags apply.
With quotes around "${cs_falcon_args}"
```
+ /opt/CrowdStrike/falconctl -s -f '--cid=<CIDRemoved> --tags=test1,test2,test3/tag'`
```
When verifying:
```
/opt/CrowdStrike/falconctl -g --tags
Sensor grouping tags are not set.
```
After change: 
```
+ /opt/CrowdStrike/falconctl -s -f --cid=<CIDRemoved> --tags=test1,test2,test3/tag
```
Verifying:
```
/opt/CrowdStrike/falconctl -g --tags
tags=test1,test2,test3/tag.
```
> Linux install script fix for when multiple tags applied

- powershell/migrate/README.md
- powershell/migrate/falcon_windows_migrate.ps1
This PR moves TLS 1.2 enablement to the top to ensure the endpoint can run the script. Also fixes an issue with using the wrong logging method.
> fix(migrate): set tls upfront + change log method

- bash/containers/falcon-container-sensor-pull/README.md
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This pull request implements a significant refactor to the `falcon-container-sensor-pull.sh` script and the corresponding README to enhance usability and maintainability. The changes primarily revolve around how sensor types are selected for download.
**Changes Introduced:**
- Replaced the individual flags `-n`, `--node`, `--kubernetes-admission-controller`, and `--kubernetes-protection-agent` with a single option, `-t`, `--type <SENSOR_TYPE>`. This option allows users to specify which sensor to download with a more concise and maintainable syntax. 
- Ensured backward compatibility for the replaced flags. This update includes a depraction warning to prepare users for the future removal of the cli args.
- Added a detailed "Sensor Types" section to the README, providing users with a …
> Simplify and Enhance Sensor Type Selection in Falcon Container Sensor Pull Script

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes #215 
This PR add the ability to use the `-p|--platform` argument to filter the list of tags.
**\*update\***
After chatting with some folks, I think it's best to keep the original json output because there is an existing workflow already established with tools such as jq that make it easier for consumers to get specific data. 
The new changes keeps the original output in place, but provides the additional platform filtering.
> feat(container-sensor-pull): add ability to filter tags by platform

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
- Adding an error message when ART_PASSWORD is empty
Solving issues when ART_PASSWORD is empty, creating this error : `ERROR: /usr/bin/docker login failed. Error message: Error: Cannot perform an interactive login from a non TTY device` 
guiding the user about the source of the issue.
- Moved the credentials-dump before the docker login (no need to perform a docker login when we request a dump-credentials)
> fix: Adding error message on CS registry password api issue and optimizing cred-dump output

- bash/install/falcon-linux-install.sh
Fixes install script for Azure instances so that it doesn't try to use AWS SSM instance information.
> fix: azure metadata service changed error codes

- molecule/pwsh_migrate/prepare.yml
Fixes issue with migration script since it calls the install script first so we need to pass in Cloud.
> fix: update prepare.yml in migrate ci

- .gitignore
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes #226 
This PR introduces a new function that better manages listing/formatting tags. For reasons unknown to me at this point, kpagent does not return sorted versions 🤷🏼‍♂️ so we needed a way to solve that. With these changes, kpagent will return back it's tags in the same sorted fashion as the others do. 
Before:
```json
{
"name" : "kpagent",
"tags": [ "0.1473.0", 
"0.1647.0", 
"0.248.0", 
"0.43.24", 
"0.447.0", 
"0.457.0", 
"0.585.0", 
"0.69.3", 
"0.852.0", 
"0.917.0" ]
}
```
After:
```json
{
"name" : "kpagent",
"tags": [ "0.43.24", 
"0.69.3", 
"0.248.0", 
"0.447.0", 
"0.457.0", 
"0.585.0", 
"0.852.0", 
"0.917.0", 
"0.1473.0", 
"0.1647.0"]
}
```
> fix: allow sorting for kpagent

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes #234 
~~This commit refactors the code to allow any container tool to list tags and take advantage of the new list_tags function. This simplifies the case for listing tags as well as downloading tags. Since a container tool is no longer needed to query tags - we can omit those case statements.~~
The original commit removed the need of using container tools (podman/skopeo) natively to fetch the tags. While that approach was simpler in terms of formatting/output, it did introduce an additional authentication layer that is not necessary for those tools. The new commits now support fetching tags via all 3 runtimes using their respective ways to fetch tags. 
To keep things uniform, and to enhance the existing `--list-tags` output, I decided to control the JSON output itself. Working …
> feat: add support for listing tags for podman/skopeo

- .github/workflows/bash_install.yml
- .github/workflows/bash_install_decrement.yml
- .github/workflows/bash_install_only.yml
- .github/workflows/bash_install_policy.yml
CI is failing because `suse-sles-15-sp4-v????????-hvm*` is no longer valid.
> chore: update sles ec2 image for workflows

- bash/containers/falcon-container-sensor-pull/README.md
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Closes #199
This PR introduces support for downloading/pushing the Falcon Snapshot scanner image.
Example Output for listing tags:
```bash
❯ bash bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh -t falcon-snapshot --list-tags        
{
"name": "cs-snapshotscanner",
"tags": [
"0.4.0",
"0.15.0",
"0.20.0"
]
}
```
> feat(container-pull-script): add support for falcon snapshot scanner

- bash/containers/falcon-container-sensor-pull/README.md
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Often DevOps team don't have an access to the Falcon Console, they need a way to get important values (like the CID) to setup the falcon-sensor/falcon-container/kpagent config.
a condition was added to check if the sensor type is kpagent as there is a special format (lowercase no checksum) compared to other sensor type.
> Add the param to get the correct CID depending the agent-type

- bash/containers/falcon-container-sensor-pull/README.md
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Get image repository and latest tag without downloading image or listing all tags
Today it's not possible to get the image full path info without downloading the image.
really simple to use for end users to get the correct image path (which is useful also for automation).
> Get image repository and latest tag without downloading image

- bash/containers/falcon-container-sensor-pull/README.md
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This commit introduces the new image assessment at runtime image. No additional scopes are needed.
> feat(container-sensor-pull): add IAR type

- bash/install/falcon-linux-install.sh
Fixes #273
This issue presents itself with very old versions of Apt < 1.1. To address this, the traditional way to install a local deb package was to use dpkg first, which would then error if any deps are needed, which is true in our case. Then afterwards you could install all with apt-get install -f flag.
> fix(bash_install): fix issue when installing with ubuntu 14

- powershell/install/falcon_windows_install.ps1
- powershell/migrate/falcon_windows_migrate.ps1
Fixes #276
This PR removes the .ToLower() from the $SensorUpdatePolicyName as it is not needed due to name.raw field being case sensitive.
> fix(pwsh): remove toLower func for policy name

- bash/install/README.md
- bash/install/falcon-linux-uninstall.sh
This PR adds the functionality to the bash script to remove the respective host from the Crowdstrike console when uninstalling the Falcon sensor.
#275
> Adds functionality to hide host from the Crowdstrike console when uninstalling.

- bash/install/falcon-linux-install.sh
On most (or all) platforms that use systemd, a SysVinit compatibility script is provided at `/usr/sbin/service`. When one runs /usr/sbin/service it works but issues a warning like "redirecting to systemctl".
The falcon-linux-install.sh script, tests for `service` first, and then `systemctl`. Because of the compatibiliity script, the `service` conditional always matches, even on modern systemd systems. Thus systemd systems always use the compatibility script and always issue the "redirecting to systemctl" message. It is more ideal to just use systemctl on a systemd system.
This patch reverses the tests, checking `systemctl` first, which is obviously the most common case and then checking for `service` second. On systemd-based systems this will result in the best behaviour, using systemctl …
> falcon-linux-install.sh: fix ordering of restart type

- bash/containers/falcon-container-sensor-pull/DEPRECATION.md
- bash/containers/falcon-container-sensor-pull/README.md
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
- Multi-architecture support has been added to the Falcon Container Sensor Pull script, enabling compatibility with mixed platform k8s clusters or environments.
- The script now supports the following enhancements:
- Copying a multi-arch image from CrowdStrike to another registry
- Copying a specific architecture from a multi-arch image from CrowdStrike to another registry
- Pulling a specific architecture from a multi-arch image locally
- `--list-tags` now supports displaying multi-arch images, whether you specify a platform or not.
- The README has been updated to reflect the deprecated features, upcoming changes, and multi-architecture support enhancements.
- Detailed usage examples and security recommendations have been added to facilitate user understanding and adoption.
- …
> feat(container-pull): add support for multi arch

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes an issue where the original logic was flawed due to naming conventions amongst our container images.
Fixes #296
> fix(container-pull): fix multi-arch logic

- .github/workflows/shell_format.yml
Previous runs of this would cause reviewdog to fail since it didn't have permissions to update the PR to show the issues found.
> ci: update shfmt to allow reviewdog access to update pr

- powershell/install/README.md
- powershell/install/falcon_windows_install.ps1
- powershell/install/falcon_windows_uninstall.ps1
Add functionality to retrieve, and use a pre-generated auth token for authentication in powershell scripts.
#211
> Add functionality to retrieve, and use a pre-generated auth token for authentication in powershell scripts.

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes #316
This PR adds the ability to auto-detect the container runtime tool when not explicitly specified. Prior to this, it would simply default to docker without checking to see if any other tools were installed. Now we go in order -> Docker -> Podman -> Skopeo in the event that more than one tool is installed.
> feat(container-pull): auto-detect container tool when not specified

- powershell/install/falcon_windows_install.ps1
Closes #319
Fixes an issue where the $errOut message was null because it didn't exist from the process itself. Now we check and handle that case. Also fixes an issue with the default ProvWaitTime. It was not set in milliseconds, so technically it was waiting for 1.2 seconds instead of the default 20 minutes 😮‍💨
> fix(windows_install): add better error handling around exitcode

- powershell/install/falcon_windows_install.ps1
This was a regression from a previous commit.
Fixes #322
> fix(windows_install): remove tolower() from update policy name

- bash/containers/falcon-container-sensor-pull/README.md
- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
- bash/install/README.md
- bash/install/falcon-linux-install.sh
- bash/install/falcon-linux-uninstall.sh
- powershell/install/README.md
- powershell/install/falcon_windows_install.ps1
- powershell/install/falcon_windows_uninstall.ps1
- powershell/migrate/README.md
- powershell/migrate/falcon_windows_migrate.ps1
This new release adds the missing files from the 1.5.0 release
> chore: bump to 1.5.1 due to missed files from last release

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes issue with listing tags associated with the new multi-arch image for 7.17
> fix(container-pull): hotfix to fix new issue with multi-arch tagging

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes #336 
Adds error handling for curl similar to our other bash installation scripts. Adds a `-f` option to ensure curl fails and returns a code.
> fix(container-pull-script): fixes issue with curl errors not being handled properly

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
This prevents govcloud users from having a correct pull token generated.
> fix(container-pull): fixes issue with hardcoded registry for pull token

- .github/workflows/release.yml
Fixes #333 
This will now ensure that on releases, we create a sha256sum of each artifact and add it to a new release artifact.
> ci: add checksum.txt release artifact

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
The sensor version gets translated from UPPER:lower before being used. I believe this was to do further processing on it and to ensure some form of consistent format. Either way, the grep of the SENSOR_VERSION variable needs to be case insensitive - allowing a user to pass in a sensor version, whether it be x.y, x.y.z-patch or the full name.
Fixes #340
> fix(container-pull): fixes issue with passing full sensor version

- bash/install/README.md
- bash/install/falcon-linux-install.sh
- bash/install/falcon-linux-uninstall.sh
Fixes #355 
This PR introduces the ability to now prepare the Falcon sensor to be
created as a gold image/template. It also fixes some minor output
issues.
> feat(bash install): add ability to prepare the sensor for gold images

- bash/install/README.md
- bash/install/falcon-linux-install.sh
Fixes #354 
This PR introduces the ability to retrieve your provisioning token from the API, the same we can retrieve the CID. Per security reasons, it may not be logical to expose your installation tokens in plain-text, so this way can do it "behind" the scene.
The way this works is (assuming you do not pass in a provisioning-token):
1. We check your existing token settings
1. If installation tokens are required in your CID:
1. We grab a token ID
1. We grab the value from the token ID
1. We set that as the provisioning-token   
So we only do something if tokens are required, which is the key here.
> feat(bash install): add api retrieval for provisioning token

- bash/install/README.md
- bash/install/falcon-linux-install.sh
- bash/install/falcon-linux-uninstall.sh
Fixes #357
This PR introduces the -h|--help flag as the only positional parameter to be accepted, without erroring out in case other positional parameters happen to be passed. This also has the added benefit of quickly printing out the usage menu without having to process anything else.
> fix(bash install): fix issue with positional param usage

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Rather than doing a grep -qw to check for just 403, we have other checks similar to this that check for the term 'authorization failed'. This keeps it inline with that.
> fix(container-pull): checking for 403 can cause issues if CID has that value

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Fixes #369
This PR allows users to list tags without needed a container runtime. This use-case is valid as we don't require a container runtime to list tags since its based on an API call.
> fix(container-pull-script): allows list tags w/o container runtime

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
sort -C is not supported in busybox, which is used in alpine linux
> Support busybox

- powershell/install/falcon_windows_install.ps1
- powershell/migrate/falcon_windows_migrate.ps1
> fix(pwsh): add missing '/' to error message for oauth2

- powershell/install/falcon_windows_install.ps1
- powershell/install/falcon_windows_uninstall.ps1
Fixes #390
This PR allows the powershell scripts to use the -GetAccessToken feature without failing due to the checks we had in place for the sensor being installed/uninstalled and having admin privs.
> fix(pwsh): allow getaccess token to run w/o priv or existing installer

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
Hi!
I noticed that I was always setting this -c parameter, even though it doesn't make sense. After I removed it, I received an error, which I think is a bug.
Cheers
Ruwen
> fix(container-pull): support skopeo and get-image-path

- bash/install/falcon-linux-install.sh
Fixes #412
This PR adds support for CentOS Stream Linux distros
> fix(bash install): add support for CentOS Stream

- bash/install/falcon-linux-install.sh
- bash/install/falcon-linux-uninstall.sh
fixes 374
This PR introduces a method of ensuring that we don't perform package management operations if the package manager is currently locked due to other operations happening.
> fix(bash install): add package lock checks to prevent premature failure

- bash/install/falcon-linux-install.sh
- bash/install/falcon-linux-uninstall.sh
- powershell/install/falcon_windows_install.ps1
- powershell/install/falcon_windows_uninstall.ps1
- powershell/migrate/falcon_windows_migrate.ps1
Closes #415 
This PR introduces a new variable that can allow for appending a custom user-agent string to use for insights metrics. While mostly aimed for internal usage, this follow RFC convention by appending the provided user-agent string to the default user-agent string.
> feat: allow user-agent string to be customizable

- bash/install/README.md
- bash/install/falcon-linux-uninstall.sh
Closes #423
This PR adds the ability to either pass a maintenance token or allow the API to retrieve it for you (assuming you have the proper scope and pass in the API creds).
> feat(uninstall bash): add maintenance token functionality for Linux

- bash/containers/falcon-container-sensor-pull/falcon-container-sensor-pull.sh
```shell
if [[ "$SENSOR" =~ "lumos" && "$REL" =~ "stage" ]]; then
STYPE="container"
EU1_PATH="falcon-container/eu1/${REL}/falcon-sensor"
US1_PATH="falcon-container/us1/${REL}/falcon-sensor"
US2_PATH="falcon-container/us2/${REL}/falcon-sensor"
GOV1_PATH="falcon-container/gov1/${REL}/falcon-sensor"
GOV2_PATH="falcon-container/gov2/${REL}/falcon-sensor"
elif [[ "$SENSOR" =~ "lumos" && "$REL" =~ "release" ]]; then
STYPE="container"
EU1_PATH="falcon-container/eu-1/${REL}/falcon-sensor"
US1_PATH="falcon-container/us-1/${REL}/falcon-sensor"
US2_PATH="falcon-container/us-2/${REL}/falcon-sensor"
GOV1_PATH="falcon-container/gov1/${REL}/falcon-sensor"
GOV2_PATH="falcon-container/gov2/${REL}/falcon-sensor"
elif [[ "$SENSOR" =~ "daemonset" ]]; then
STYPE="falcon-linux" …
```
> In case falcon-container stage commercial path should be us1/us2/eu1

- .github/workflows/bash_install.yml
- .github/workflows/bash_install_decrement.yml
- .github/workflows/bash_install_only.yml
- .github/workflows/bash_install_policy.yml
- .github/workflows/bash_migrate.yml
Debian 11 is now in LTS mode with limited support and the backports are decommissioned
> ci: remove debian-11 from test matrix
